apiVersion: v1
kind: ConfigMap
metadata:
  namespace: smart-healthcare
  name: service-prescription-config
  labels:
    app: service-prescription
data:
  SPRING_APPLICATION_NAME: "service-prescription"
  SERVER_PORT: "8088"
