spring.application.name=service-doctor
server.port=8082

spring.datasource.url= jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.eqlurxjkztfbmpczqpno
spring.datasource.password=I90db2bRdQpTYD4u
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.default_schema=doctor_service
spring.jpa.show-sql=true
management.endpoints.web.exposure.include=health,info
logging.level.org.hibernate.SQL=info
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
