spring.application.name=service-doctor
server.port=8082

# Load local env file
spring.config.import=optional:file:.env.local[.properties],optional:file:service-doctor/.env.local[.properties]

spring.datasource.url=${DOCTOR_DB_URL}
spring.datasource.username=${DOCTOR_DB_USERNAME}
spring.datasource.password=${DOCTOR_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=${DOCTOR_DB_DDL_AUTO:update}
spring.jpa.properties.hibernate.default_schema=${DOCTOR_DB_SCHEMA:doctor_service}
spring.jpa.show-sql=${DOCTOR_DB_SHOW_SQL:true}
management.endpoints.web.exposure.include=health,info
logging.level.org.hibernate.SQL=info
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Hikari Protocol
spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=1


# JWT Security
application.security.jwt.secret-key=${APPLICATION_SECURITY_JWT_SECRET_KEY:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
# 24 hours in milliseconds
application.security.jwt.expiration=${APPLICATION_SECURITY_JWT_EXPIRATION:86400000}
# 7 days in milliseconds
application.security.jwt.refresh-token.expiration=${APPLICATION_SECURITY_JWT_REFRESH_EXPIRATION:604800000}