services:
  kafka:
    image: redpandadata/redpanda:latest
    container_name: smart-healthcare-kafka
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp
      - "1"
      - --memory
      - 1G
      - --reserve-memory
      - 0M
      - --node-id
      - "0"
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:29092
      - --advertise-kafka-addr
      - PLAINTEXT://localhost:29092
    ports:
      - "29092:29092"
