spring.application.name=api-gateway
server.port=8080

spring.cloud.gateway.mvc.routes[0].id=patient-service
spring.cloud.gateway.mvc.routes[0].uri=${PATIENT_SERVICE_URL:http://localhost:8081}
spring.cloud.gateway.mvc.routes[0].predicates[0]=Path=/api/v1/patients/**

spring.cloud.gateway.mvc.routes[1].id=admin-service
spring.cloud.gateway.mvc.routes[1].uri=${ADMIN_SERVICE_URL:http://localhost:8087}
spring.cloud.gateway.mvc.routes[1].predicates[0]=Path=/api/v1/admin/**
