spring.application.name=api-gateway
server.port=8080

# Route for Telemedicine Service (Spring Cloud Gateway Server WebMVC)
spring.cloud.gateway.server.webmvc.routes[0].id=telemedicine-service
spring.cloud.gateway.server.webmvc.routes[0].uri=http://localhost:8085
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/telemedicine/**
