spring.application.name=api-gateway
server.port=8080

# Route for Telemedicine Service
spring.cloud.gateway.routes[0].id=telemedicine-service
spring.cloud.gateway.routes[0].uri=http://localhost:8085
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/telemedicine/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=2
