apiVersion: v1
kind: Secret
metadata:
  name: payment-secrets
type: Opaque
stringData:
  db-url: "your_db_url"
  db-user: "your_db_user"
  db-password: "your_db_password"
  payhere-merchant-id: "your_merchant_id"
  payhere-merchant-secret: "your_merchant_secret"