apiVersion: v1
kind: ConfigMap
metadata:
  namespace: smart-healthcare
  name: service-doctor-config
  labels:
    app: service-doctor
data:
  SPRING_APPLICATION_NAME: "service-doctor"
  SERVER_PORT: "8082"
