apiVersion: v1
kind: Secret
metadata:
  namespace: smart-healthcare
  name: doctor-database-secret
  labels: 
    app: service-doctor
type: Opaque
stringData:
  DB_URL: "jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:5432/postgres?sslmode=require"
  DB_USER: "postgres.eqlurxjkztfbmpczqpno"
  DB_PASSWORD: "I90db2bRdQpTYD4u"

