apiVersion: v1
kind: Service
metadata:
  name: telemedicine-service
  namespace: smart-healthcare
  labels:
    app: telemedicine-service
spec:
  selector:
    app: telemedicine-service
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
  type: ClusterIP