apiVersion: v1
kind: ConfigMap
metadata:
  name: telemedicine-config
  namespace: smart-healthcare
data:
  SPRING_PROFILES_ACTIVE: "prod"
  SERVER_PORT: "8085"
  # Add other non-sensitive environment variables here (e.g., DB URLs)