apiVersion: apps/v1
kind: Deployment
metadata:
  name: telemedicine-deployment
  labels:
    app: telemedicine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telemedicine
  template:
    metadata:
      labels:
        app: telemedicine
    spec:
      containers:
        - name: telemedicine-service
          image: smarthealth/telemedicine-service:latest # Replace with your actual Docker image name
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080 # Update if your Spring Boot app runs on a different port
          envFrom:
            - configMapRef:
                name: telemedicine-config