apiVersion: v1
kind: Service
metadata:
  name: telemedicine-service
spec:
  selector:
    app: telemedicine
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP # Keeps the service internal so only the API Gateway can access it