spring.application.name=service-payment
server.port=8084
spring.config.import=optional:file:.env[.properties],optional:file:.env.local[.properties],optional:file:service-payment/.env.local[.properties]

# Load local env file
# PostgreSQL - Supabase (hard-coded from .env.local)
# DB_URL=jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:6543/postgres?currentSchema=payment_service
# DB_USER=postgres.gbtcjljhgpypxakchkes
# DB_PASSWORD=3ORV744nFlVvIWqx
spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:6543/postgres?currentSchema=payment_service
spring.datasource.username=postgres.gbtcjljhgpypxakchkes
spring.datasource.password=3ORV744nFlVvIWqx
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.schema=payment_service
spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=1


spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=payment_service
spring.jpa.show-sql=true

# PayHere (hard-coded from .env.local)
payhere.merchant.id=4OVycDcfsxM4JH5F1mmFxF3Xf
payhere.merchant.secret=4TpzFpMv9hl4ExBYgjdW2G4Ob7lFOFaHX4Uv3dSM9fBz
payhere.sandbox=true
payhere.base.url=https://sandbox.payhere.lk/pay/checkout

# Kafka (hard-coded from .env.local)
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.consumer.group-id=payment-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always

management.health.db.enabled=false
management.health.kafka.enabled=false
