spring.application.name=service-prescription
server.port=8088

spring.datasource.url= ${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.default_schema=prescription_service
spring.jpa.show-sql=true
management.endpoints.web.exposure.include=health,info
logging.level.org.hibernate.SQL=info
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

