spring.application.name=service-prescription
server.port=8088

# Load local env file
spring.config.import=optional:file:.env.local[.properties],optional:file:service-prescription/.env.local[.properties]

spring.datasource.url= ${PRESCRIPTION_DB_URL}
spring.datasource.username=${PRESCRIPTION_DB_USERNAME}
spring.datasource.password=${PRESCRIPTION_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.default_schema=prescription_service
spring.jpa.show-sql=true
management.endpoints.web.exposure.include=health,info
logging.level.org.hibernate.SQL=info
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Hikari Protocol
spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=1


# JWT Security
application.security.jwt.secret-key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
# 24 hours in milliseconds
application.security.jwt.expiration=86400000
# 7 days in milliseconds
application.security.jwt.refresh-token.expiration=604800000

# Service URLs
service.doctor.url=http://localhost:8082/api/v1/doctors
service.appointment.url=http://localhost:8083/api/v1/appointments

# WebClient timeout settings
spring.webflux.webclient.max-in-memory-size=10MB

