spring.application.name=service-appointment
server.port=8083

spring.datasource.url= ${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.default_schema=appointment_service
spring.jpa.show-sql=true
management.endpoints.web.exposure.include=health,info
logging.level.org.hibernate.SQL=info