spring.application.name=service-appointment
server.port=8083
spring.config.import=optional:file:./telemedicine.env[.properties]

spring.datasource.url= ${APPOINTMENT_DB_URL}
spring.datasource.username=${APPOINTMENT_DB_USERNAME}
spring.datasource.password=${APPOINTMENT_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.default_schema=appointment_service
spring.jpa.show-sql=true
management.endpoints.web.exposure.include=health,info
logging.level.org.hibernate.SQL=info
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JWT Security
application.security.jwt.secret-key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
# 24 hours in milliseconds
application.security.jwt.expiration=86400000
# 7 days in milliseconds
application.security.jwt.refresh-token.expiration=604800000

# Service URLs
service.patient.url=http://localhost:8081/api/v1/patients
service.doctor.url=http://localhost:8082/api/v1/doctors

# WebClient timeout settings
spring.webflux.webclient.max-in-memory-size=10MB

telemedicine.service.url=${TELEMEDICINE_SERVICE_URL:http://localhost:8085/api/v1/telemedicine/sessions}
