apiVersion: v1
kind: Secret
metadata:
  name: patient-service-secret
  namespace: smart-healthcare
  labels:
    app: patient-service
type: Opaque
stringData:
  PATIENT_DB_URL: "jdbc:postgresql://db.xxxxx.supabase.co:5432/postgres"
  PATIENT_DB_USERNAME: "postgres"
  PATIENT_DB_PASSWORD: "your-actual-password"
